@extends('page')

@section('pagetitle')
字典管理
@stop
@section('toolbar')
    <wd:button id="btn_new_dict" skin="primary" title="新增字典"></wd:button>
@stop

@section('pageContent')
<style>
.folder-list li.active  {
    background-color: #4374e0;
}
.folder-list li.active a{
    color: #ffffff;
}
</style>
     <div id="dict_page" class="row" ms-controller="dictController">   
        <div class="col-lg-4">
            <wd:ibox class="float-e-margins">
                <wd:ibody>
                    <div class="file-manager">
                        <wd:text id="keyword" ms-duplex="keyword" placeholder="搜索关键字" ms-on-keyup="search">
                            <wd:addon place="before"><i class="fa fa-search"></i></wd:addon>
                        </wd:text>
                        <div class="hr-line-dashed"></div>
                        <ul class="folder-list m-b-md" style="padding: 0">
                            <li ms-repeat="dicts" ms-class="active:el.id==dict.id"><a href="javascript:void(0)" ms-click="getDict($event, $index)" ms-attr-data-id="@{{el.id}}"> <i class="fa fa-inbox "></i> @{{el.title}} [@{{el.name}}] </a></li>
                        </ul>
                        <div id="dict_pagination"></div>
                        <div class="clearfix"></div>
                    </div>
                </wd:ibody>
            </wd:ibox>
        </div>
        <div class="col-lg-8" id="panel_right">
            <wd:tabpanel id="dict_tabpanel">
                <wd:tab title="字典信息" active="true" id="box_dict">
                    <wd:form id="form_edit" layout="form-horizontal" ms-on-submit="saveDict">
                        <wd:text id="name" name="name" title="代码" placeholder="字典代码" ms-duplex="dict.name" required="true"></wd:text>
                        <wd:text name="title" title="名称" placeholder="字典名称" ms-duplex="dict.title" required="true"></wd:text>
                        <wd:select name="module" title="所属模块" options="{{Wedo\Core\Application::app()->getModules()}}" ms-duplex="dict.module" required="true" use-label="true"></wd:select>
                        <wd:inputgroup>
                            <wd:button type="submit" title="保存" skin="primary"></wd:button>
                            &nbsp;&nbsp;
                            <wd:button id="btn_delete_dict" title="删除" skin="danger" ms-on-click="deleteDict" class="hide"></wd:button>
                        </wd:inputgroup>
                    </wd:form>  
                </wd:tab>
                <wd:tab title="字典项" id="box_items" class="hide">
                    <div class="table-responsive">
                        <table id="table_items" class="table table-stripped table-bordered">
                            <thead>
                                <tr>
                                    <th class="col-md-4"> Label </th>
                                    <th class="col-md-4"> Value </th>
                                    <th class="col-md-2"> Order </th>
                                    <th class="col-md-2 text-center"> Actions </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr ms-repeat="items" ms-on-dblclick="editItem($event, $index)">
                                    <td>
                                        <wd:text name="title" placeholder="Label" ms-attr-value="el.title" required="true" ms-if="el.writable"></wd:text>
                                        <span ms-if="! el.writable">@{{el.title}}</span>
                                        <wd:hidden name="id" ms-attr-value="el.id"></wd:hidden>
                                    </td>
                                    <td>
                                        <wd:text name="value" placeholder="Value" ms-attr-value="el.value" required="true" ms-if="el.writable"></wd:text>
                                        <span ms-if="!el.writable">@{{el.value}}</span>
                                    </td>
                                    <td>
                                        <wd:text name="display_order" placeholder="Display Order" ms-attr-value="el.display_order" ms-if=" el.writable"></wd:text>
                                        <span ms-if="!el.writable">@{{el.display_order}}</span>
                                    </td>
                                    <td align="center">
                                        <wd:button size="sm" skin="primary" ms-on-click="editItem($event, $index)" ms-if="!el.writable"><i class="fa fa-edit"></i> </wd:button>
                                        <wd:button size="sm" skin="primary" ms-on-click="saveItem($event, $index)" ms-if="el.writable"><i class="fa fa-save"></i> </wd:button>
                                        <wd:button size="sm" skin="danger" ms-on-click="deleteItem($event, $index)"><i class="fa fa-trash"></i> </wd:button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="row text-center">
                        <wd:button id="btn_add_row" title="添加行" skin="primary" ms-on-click="addItem"></wd:button>
                    </div>
                </wd:tab>
            </wd:tabpanel>
        </div>
    </div>    
@stop

@section('pageScript')
{!!loadJs('dict/dict.js')!!}
@stop