@extends('page')

@section('pagetitle')
DB帐号管理
@stop
@section('toolbar')
    <wd:button id="btn_add" skin="primary" title="新增"></wd:button>
@stop

@section('pageContent')
     <div id="db_page" class="row" ms-controller="dbController">
        <wd:tabpanel id="dict_tabpanel" class="m-b-sm border-bottom">
            <wd:tab title="列表" active="true" id="box_list">
                <wd:form layout="form-inline">
                    <wd:text id="keyword" ms-duplex="keyword" placeholder="搜索关键字" ms-on-keyup="search">
                        <wd:addon place="before"><i class="fa fa-search"></i></wd:addon>
                    </wd:text>
                </wd:form>
            </wd:tab>
            <wd:tab title="编辑" id="box_edit">
                <wd:form id="form_edit" layout="form-horizontal" ms-on-submit="saveDict">
                    <wd:text id="name" name="name" title="代码" placeholder="字典代码" ms-duplex="obj.name" required="true"></wd:text>
                    <wd:text name="title" title="名称" placeholder="字典名称" ms-duplex="obj.title" required="true"></wd:text>
                    <wd:select name="module" title="所属模块" options="{{Wedo\Core\Application::app()->getModules()}}" ms-duplex="obj.module" required="true" use-label="true"></wd:select>
                    <wd:inputgroup>
                        <wd:button type="submit" title="保存" skin="primary"></wd:button>
                        &nbsp;&nbsp;
                        <wd:button id="btn_delete_dict" title="删除" skin="danger" ms-on-click="deleteDict" class="hide"></wd:button>
                    </wd:inputgroup>
                </wd:form>  
            </wd:tab>
        </wd:tabpanel>
        <div class="row">
            <div class="col-lg-12">
                <wd:ibox>
                    <wd:ibody>
                        <wd:table id="db_table" ds="items" primary-key="id" pagination="true">
                            <wd:cell name="id" label="ID" width="2"></wd:cell>
                            <wd:cell name="username" label="用户名" width="4"></wd:cell>
                            <wd:cell name="password" label="密码" width="4"></wd:cell>
                            <wd:cell name="dbname" label="数据库名" width="4"></wd:cell>
                            <wd:cell name="host" label="IP" width="4"></wd:cell>
                            <wd:cell name="memo" label="备注" width="4"></wd:cell>
                        </wd:table>
                    </wd:ibody>
                </wd:ibox>

            </div>
        </div>
    </div>    
@stop

@section('pageScript')
{!!loadJs('db/index.js')!!}
@stop