@extends('page')

@section('pagetitle')
菜单管理
@stop
@section('toolbar')
    <wd:button skin="primary" id="btn_add_top" size="ms" title="新增一级菜单"></wd:button>
@stop

@section('pageContent')
     <div class="row">   
        <div class="col-lg-3">
            <wd:ibox class="float-e-margins">
                <wd:ibody>
                    <div id="menutree"></div>                    
                </wd:ibody>
            </wd:ibox>
        </div>
        <div class="col-lg-9" id="panel_right" ms-controller="menu">
            <div id="top_category_panel">
                <wd:ibox>
                    <wd:iheader title="新增一级分类"></wd:iheader>
                    <wd:ibody>
                        <wd:form layout="form-inline" ms-on-submit="addCategory">
                            <wd:text name="name" title="分类名称" placeholder="分类名称" ms-duplex="sub.name" required="true"></wd:text>
                            <wd:button type="submit" title="保存" skin="primary"></wd:button>
                        </wd:form>   
                    </wd:ibody>
                </wd:ibox>
            </div>
            <div id="menu_panel" class="hide">
                <wd:tabpanel id="tab_category">
                    <wd:tab title="菜单" active="true">
                        <wd:form id="category_edit_form" layout="form-inline" ms-on-submit="rename">
                            <wd:text name="name" title="菜单名称" placeholder="菜单名称" ms-duplex="category.name" required="true"></wd:text>
                            <wd:hidden name="id" ms-duplex="category.id"></wd:hidden>
                            <wd:button type="submit" title="重命名" skin="primary"></wd:button>
                            <wd:button ms-click="deleteCategory" title="删除" skin="danger"></wd:button>
                        </wd:form> 
                    </wd:tab>
                    <wd:tab title="新增下级菜单">
                        <wd:form id="category_sub_form" layout="form-inline" ms-on-submit="addCategory">
                            <wd:text name="name" title="下级菜单名称" placeholder="下级菜单名称" ms-duplex="sub.name" required="true"></wd:text>
                            <wd:button type="submit" title="保存" skin="primary"></wd:button>
                        </wd:form>  
                    </wd:tab>
                    <wd:tab title="新增菜单项">
                        <div class="alert alert-info" role="alert">
                            勾选以下的功能增加到左边选中的分类下
                        </div>
                        <div id="functiontree"></div>    
                    </wd:tab>
                </wd:tabpanel>
            </div>
            <div id="function_panel" class="hide">
                <wd:tabpanel id="fun_panel">
                    <wd:tab title="功能信息" active="true">
                        <wd:form id="edit_fun_form" layout="form-horizontal" ms-on-submit="updateFunction">
                            <wd:text name="name" title="代码" ms-duplex="fun.name" readonly="true"></wd:text>
                            <wd:text name="title" title="功能名称" ms-duplex="fun.title" required="true"></wd:text>
                            <wd:text name="url" title="URL" ms-duplex="fun.url" required="true"></wd:text>
                            <wd:inputgroup>
                                <wd:button type="submit" skin="primary" title="修改"></wd:button>
                                &nbsp;
                                <wd:button ms-click="deleteFunction" title="删除" skin="danger"></wd:button>
                            </wd:inputgroup>
                        </wd:form> 
                    </wd:tab>
                    <wd:tab title="权限项">
                        <div class="row">
                            
                        </div>
                    </wd:tab>
                </wd:tabpanel>
            </div>
        </div>
    </div>    
@stop

@section('pageScript')
{!!loadJs('menu/menu.js')!!}
@stop