@extends('page')

@section('pagetitle')
功能管理
@stop
@section('toolbar')
    <wd:button skin="primary" id="btn_add_first">新增一级分类</wd:button>
@stop

@section('pageContent')
     <div class="row" ms-controller="category">   
        <div class="col-lg-3">
            <wd:ibox class="float-e-margins">
                <wd:ibody>
                    <wd:text name="keyword" id="keyword" ms-duplex="keyword" placeholder="搜索关键字" ms-on-keyup="search">
                        <wd:addon place="before"><i class="fa fa-search"></i></wd:addon>
                    </wd:text>
                    <div class="space-25"></div>
                    <div id="function_category"></div>                    
                </wd:ibody>
            </wd:ibox>
        </div>
        <div class="col-lg-9" id="panel_right">
            <div id="top_category_panel">
                <wd:ibox>
                    <wd:iheader title="新增一级分类"></wd:iheader>
                    <wd:ibody>
                        <wd:form layout="form-inline" ms-on-submit="addCategory">
                            <wd:text name="name" title="分类名称" placeholder="分类名称" ms-duplex="sub.name" required="true"></wd:text>
                            <wd:button type="submit" title="保存" skin="primary"></wd:button>
                        </wd:form>   
                    </wd:ibody>
                </wd:ibox>
            </div>
            <div id="category_panel" class="hide">
                <wd:ibox id="category_info_panel">
                    <wd:iheader title="分类信息"></wd:iheader>
                    <wd:ibody>
                        <wd:form id="category_edit_form" layout="form-inline" ms-on-submit="rename">
                            <wd:text name="name" title="分类名称" placeholder="分类名称" ms-duplex="category.name" required="true"></wd:text>
                            <wd:hidden name="id" ms-duplex="category.id"></wd:hidden>
                            <wd:button type="submit" title="重命名" skin="primary"></wd:button>
                            <wd:button ms-click="deleteCategory" title="删除" skin="danger"></wd:button>
                        </wd:form> 
                    </wd:ibody>
                </wd:ibox>
                <wd:tabpanel id="tab_category">
                    <wd:tab title="新增下级分类" active="true">
                        <wd:form id="category_sub_form" layout="form-inline" ms-on-submit="addCategory">
                            <wd:text name="name" title="下级分类名称" placeholder="下级分类名称" ms-duplex="sub.name" required="true"></wd:text>
                            <wd:button type="submit" title="保存" skin="primary"></wd:button>
                        </wd:form>  
                    </wd:tab>
                    <wd:tab title="新增功能">
                        <wd:form id="category_fun_form" layout="form-horizontal" ms-on-submit="addFunction">
                            <wd:rdogroup name="type" title="类型" vertical="false" options="{'1':'系统内', '2': '引用外部链接'}" value="1"></wd:rdogroup>
                            <wd:text name="title" title="功能名称" ms-duplex="fun.title" required="true"></wd:text>
                            <div ms-if="fun.type==1">
                                <wd:inputgroup title="URL">
                                    <wd:text name="module" placeholder="模块" ms-duplex="fun.module" required="true">
                                    </wd:text> <span style="padding:0 10px"></span>
                                    <wd:text name="controller" placeholder="控制器" ms-duplex="fun.controller" required="true">
                                    </wd:text> <span style="padding:0 10px"></span>
                                    <wd:text name="action" placeholder="Action" ms-duplex="fun.action"></wd:text>
                                </wd:inputgroup>
                            </div>
                            <div ms-if="fun.type==2">
                                <wd:text name="name" title="代码" ms-duplex="fun.name" required="true" ></wd:text>
                                <wd:text name="url" title="URL" ms-duplex="fun.url" required="true"></wd:text>
                            </div>
                            
                            <wd:button type="submit" title="保存" skin="primary"></wd:button>
                        </wd:form>  
                    </wd:tab>
                </wd:tabpanel>
            </div>
            <div id="function_panel" class="hide">
                <wd:tabpanel id="fun_panel">
                    <wd:tab title="功能信息" active="true">
                        <wd:form id="edit_fun_form" layout="form-horizontal" ms-on-submit="updateFunction">
                            <wd:text name="title" title="功能名称" ms-duplex="fun.title" required="true"></wd:text>
                            <div ms-if="fun.type==1">
                                <wd:inputgroup title="URL">
                                    <wd:text name="module" placeholder="模块" ms-duplex="fun.module" required="true">
                                    </wd:text> <span style="padding:0 10px"></span>
                                    <wd:text name="controller" placeholder="控制器" ms-duplex="fun.controller" required="true">
                                    </wd:text> <span style="padding:0 10px"></span>
                                    <wd:text name="action" placeholder="Action" ms-duplex="fun.action"></wd:text>
                                </wd:inputgroup>
                            </div>
                            <div ms-if="fun.type==2">
                                <wd:text name="name" title="代码" ms-duplex="fun.name"></wd:text>
                                <wd:text name="url" title="URL" ms-duplex="fun.url" required="true"></wd:text>
                            </div>
                            <wd:inputgroup>
                                <wd:button type="submit" skin="primary" title="修改"></wd:button>
                                &nbsp;
                                <wd:button ms-click="deleteFunction" title="删除" skin="danger"></wd:button>
                            </wd:inputgroup>
                        </wd:form> 
                    </wd:tab>
                    <wd:tab title="权限项">
                        <div class="row text-center">
                            <div id="ri_btn_group" class="btn-group">
                                <button class="btn btn-white btn-sm" ms-click="showRightItem(el.id, $event)" ms-repeat="rightitems">@{{el.title}}</button>
                                <button class="btn btn-primary btn-sm" ms-click="newRightItem">新增权限项</button>
                            </div>
                            
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="row">
                            <div id="ri_box" >
                                <wd:form id="rightitem_form" layout="form-horizontal" ms-on-submit="saveRightItem" ms-if="rightitem.name != 'view'">
                                    <wd:text name="title" title="名称" ms-duplex="rightitem.title" required="true"></wd:text>
                                    <wd:text name="name" title="代码" ms-duplex="rightitem.name" required="true"></wd:text>
                                    <wd:textarea rows="3" name="memo" title="说明" ms-duplex="rightitem.memo"></wd:textarea>
                                    <wd:inputgroup>
                                        <wd:button type="submit" skin="primary" title="保存"></wd:button>
                                        &nbsp;
                                        <wd:button ms-click="deleteRightItem" title="删除" skin="danger" ms-if="rightitem.id > 0"></wd:button>
                                    </wd:inputgroup>
                                </wd:form>
                                <wd:form layout="form-horizontal" ms-if="rightitem.name == 'view'">
                                    <wd:text name="title" title="名称" ms-duplex="rightitem.title" readonly="true"></wd:text>
                                    <wd:text name="name" title="代码" ms-duplex="rightitem.name" readonly="true"></wd:text>
                                    <wd:textarea rows="3" name="memo" title="说明" ms-duplex="rightitem.memo" readonly="true"></wd:textarea>
                                </wd:form>
                            </div>
                        </div>
                    </wd:tab>
                </wd:tabpanel>
            </div>
        </div>
    </div>    
@stop

@section('pageScript')
{!!loadJs('function/function.js')!!}
@stop